### PR TITLE
Switch to socketio_v4

### LINKED ISSUE #6: Compatibility with new `python-socketio` and `python-engineio` versions?
I'm current working on resolving potential dependency conflicts in Home Assistant. While doing that, I noticed that the latest versions for both `python-socketio` and `python-engineio` aren't supported. For the moment, there seems to be a solution but in the long term this might conflict with [aioambient](https://github.com/bachya/aioambient/tree/dev) which also uses `socketio`. Would you be able to take a look if you can bump the dependency range?

https://github.com/jkeljo/sisyphus-control/blob/5f53068c6cbbade6bf20462710461128fa633684/setup.py#L31-L36

The current non-conflicting versions constraints (in Home Assistant).
```
python-engineio>=3.13.1,<4.0
python-socketio>=4.6.0,<5.0
```

The current constraints from `aioambient`: https://github.com/bachya/aioambient/blob/2021.11.0/pyproject.toml#L63-L64

Changelog `python-socketio`: https://github.com/miguelgrinberg/python-socketio/blob/main/CHANGES.md
Changelog `python-engineio`: https://github.com/miguelgrinberg/python-engineio/blob/main/CHANGES.md

### PR DESCRIPTION
**Pull request by bdraco**
socketio_v4 is a fork of socketio to avoid
conflicting with the socketio namespace

https://pypi.org/project/python-socketio-v4/

fixes #6

### CODE REVIEW

**Comment by jkeljo** [comment]
Thanks for doing this! I'll cut a release with this later tonight.

**Comment by bdraco** [comment]
Thanks. Feel free to ping me when its ready. I'm happy to take care of reverting https://github.com/home-assistant/core/pull/124742 and bumping the library.

**Comment by bdraco** [comment]
> Thanks for doing this! I'll cut a release with this later tonight.

@jkeljo friendly ping as I'd like to drop the breaking change from HA before 2024.9.x

**Comment by jkeljo** [comment]
My apologies, family time got distracting ;). Published now, thanks for your patience, and your help!

**Comment by bdraco** [comment]
Thanks!

**Pull request merged**
